let quote = [
    "Fortune befriends the bold. – Emily Dickinson",
    "Think big, think fast, think ahead. – Dhirubhai Ambani",
    "We only live once, so I want to think big. – Masayoshi Son",
    "Life shrinks or expands in proportion to one’s courage. – Anais Nin",
    "It’s core to Amazon’s culture that we want to innovate and think big. – Roy Price",
    "Our dreams have to be bigger. Our ambitions higher. Our commitment deeper. And our efforts greater. – Dhirubhai Ambani",
    "When Paul Allen and I started Microsoft over 30 years ago, we had big dreams about software. – Bill Gates",
    "Small aim is a crime; have great aim. – P.J. Abdul Kalam",
    "The bold adventurer succeeds the best. – Ovid",
    "Think big, but take one day at a time. – Kunal Bahl",
    "Nurture your minds with great thoughts. To believe in the heroic makes heroes. – Benjamin Disraeli",
    "Believe you can and you’re halfway there. – Theodore Roosevelt",
    "You have to believe in yourself. You need to have the audacity to be great. – Rosie Perez",
    "One person with a belief is equal to a force of 99 who have only interests. – John Stuart Mill",
    "To accomplish great things, we must not only act, but also dream; not only plan, but also believe. – Anatole France",
    "In order to succeed, we must first believe that we can. – Nikos Kazantzakis",
    "Every great advance in science has issued from a new audacity of imagination. – John Dewey",
    "Let us make our future now, and let us make our dreams tomorrow’s reality. – Malala Yousafzai",
    "Who would set a limit to the mind of man? – Galileo Galilei",
    "Our greatness lies not so much in being able to remake the world as in being able to remake ourselves. – Mahatma Gandhi",
    "The only way to do great work is to love what you do. – Steve Jobs",
    "Innovation distinguishes between a leader and a follower. – Steve Jobs",
    "Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work. – Steve Jobs",
    "The people who are crazy enough to think they can change the world are the ones who do. – Steve Jobs",
    "Stay hungry, stay foolish. – Steve Jobs",
    "Don’t be afraid to give up the good to go for the great. – John D. Rockefeller",
    "It’s not about ideas. It’s about making ideas happen. – Scott Belsky",
    "In the future, there will be no female leaders. There will just be leaders. – Sheryl Sandberg",
    "It’s not about having the right opportunities. It’s about handling the opportunities right. – Mark Cuban",
    "The best way to predict the future is to invent it. – Alan Kay",
    "Do not worry about failure; you only have to be right once. – Drew Houston",
    "Technology is best when it brings people together. – Matt Mullenweg",
    "Success is not final, failure is not fatal: It is the courage to continue that counts. – Winston Churchill",
    "The biggest risk is not taking any risk. – Mark Zuckerberg",
    "I think it’s possible for ordinary people to choose to be extraordinary. – Elon Musk",
    "I could either watch it happen or be a part of it. – Elon Musk",
    "When something is important enough, you do it even if the odds are not in your favor. – Elon Musk",
    "Great companies are built on great products. – Elon Musk",
    "If you're not part of the solution, you're part of the problem. – Eli Pariser",
    "Do not let yourself be lulled into inaction. – Anita Roddick",
    "Success is walking from failure to failure with no loss of enthusiasm. – Winston Churchill",
    "I think the biggest mistake entrepreneurs make is that they don't truly understand the problem they're solving. – Evan Williams",
    "Success is the sum of small efforts, repeated day in and day out. – Robert Collier",
    "The way to get started is to quit talking and begin doing. – Walt Disney",
    "Failure is simply the opportunity to begin again, this time more intelligently. – Henry Ford",
    "Don't be afraid to give up the good to go for the great. – John D. Rockefeller",
    "The question isn’t who is going to let me; it’s who is going to stop me. – Ayn Rand",
    "You don't have to be great to start, but you have to start to be great. – Zig Ziglar",
    "Success is not in what you have, but who you are. – Bo Bennett",
    "I never took a day off in my 20s. Not one. – Bill Gates",
    "You have to be willing to work hard and be really good at it. – Bill Gates",
    "If you are born poor, it’s not your mistake, but if you die poor, it’s your mistake. – Bill Gates",
    "We always overestimate the change that will occur in the next two years and underestimate the change that will occur in the next ten. – Bill Gates",
    "I believe that if you show people the problems and you show them the solutions they will be moved to act. – Bill Gates",
    "It’s fine to celebrate success, but it is more important to heed the lessons of failure. – Bill Gates",
    "Don’t compare yourself with anyone in this world. If you do so, you are insulting yourself. – Bill Gates",
    "Success is a lousy teacher. It seduces smart people into thinking they can’t lose. – Bill Gates",
    "The Internet is becoming the town square for the global village of tomorrow. – Bill Gates",
    "We always think we can do everything. When in fact, you can do a lot by doing fewer things really well. – Larry Page",
    "It’s more fun to be a pirate than to join the navy. – Steve Jobs",
    "Computers are incredibly fast, accurate, and stupid; humans are incredibly slow, inaccurate, and brilliant; together they are powerful beyond imagination. – Albert Einstein",
    "The great growling engine of change – technology. – Alvin Toffler",
    "Technology, like art, is a soaring exercise of the human imagination. – Daniel Bell",
    "The future of humanity depends on us making the best of technology. – Jeff Bezos",
    "It's not about being the best; it's about being better than you were yesterday. – Jeff Bezos",
    "Technology is changing everything, and it’s changing faster than ever. – Jeff Bezos",
    "Your brand is what other people say about you when you’re not in the room. – Jeff Bezos",
    "If you're not failing every now and then, it's a sign you're not doing anything very innovative. – Woody Allen",
    "You don’t learn to walk by following rules. You learn by doing, and by falling over. – Richard Branson",
    "Business opportunities are like buses, there's always another one coming. – Richard Branson",
    "Success is not about making money, it’s about making a difference. – Richard Branson",
    "You don’t have to be a genius to be successful, just someone who will not give up. – Richard Branson",
    "If you’re not enjoying what you’re doing, then you shouldn’t be doing it. – Richard Branson",
    "There’s no magic to innovation; it’s about being brave, being bold, and being fearless. – Steve Wozniak",
    "A computer is like a bicycle for the mind. – Steve Jobs",
    "Don’t let the noise of others’ opinions drown out your own inner voice. – Steve Jobs",
    "Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work. – Steve Jobs",
    "You can't connect the dots looking forward; you can only connect them looking backward. – Steve Jobs",
    "Be a yardstick of quality. Some people aren’t used to an environment where excellence is expected. – Steve Jobs",
    "Do what you love, and don't listen to anyone else who tells you not to. – Steve Jobs",
    "Don't let the noise of others' opinions drown out your own inner voice. – Steve Jobs",
    "Innovation comes from saying ‘yes’ to new ideas and not being afraid of taking risks. – Tim Cook",
    "I want to put a ding in the universe. – Steve Jobs",
    "Keep pushing forward, and let your passion drive your progress. – Elon Musk",
    "If you’re not prepared to be wrong, you’ll never come up with anything original. – Sir Ken Robinson",
    "The thing that drives me is that I want to help humanity move to the next level. – Elon Musk",
    "Success is not for the chosen few; it’s for those who are willing to make the right decisions and take consistent action. – Jack Dorsey",
    "It’s important to learn as much as you can. And be always open to new information. – Jeff Bezos",
    "The only limit to our realization of tomorrow is our doubts of today. – Franklin D. Roosevelt",
    "If you're not part of the solution, you're part of the problem. – Eli Pariser",
    "Nothing will work unless you do. – Maya Angelou",
    "Success is a lousy teacher. It seduces smart people into thinking they can’t lose. – Bill Gates",
    "What we’re trying to do is not just create a company, but create a new kind of company. – Jeff Bezos",
    "The way to get started is to quit talking and begin doing. – Walt Disney",
    "Sometimes it’s not the technology that makes the difference; it’s the mindset. – Marc Benioff",
    "Every great idea starts with a spark of passion and imagination. – Mark Zuckerberg",
    "Great things in business are never done by one person. They’re done by a team of people. – Steve Jobs",
    "If you’re not failing every now and then, you’re not being innovative enough. – Elon Musk",
];

let RandomIndex = [];

let genratequote = function () {
    if (RandomIndex.length === quote.length) {
        RandomIndex = [];
    }

    let random;
    do {
        random = Math.floor(Math.random() * quote.length); // Corrected to use quote.length
    } while (RandomIndex.includes(random));

    let QuoteElement = document.getElementById("quote");
    QuoteElement.innerHTML = quote[random];
    RandomIndex.push(random);
};
